apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: frontend-api
    spec:
      containers:
      - name: frontend-api
        image: frontend-api:${VERSION}
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-api
spec:
  type: NodePort
  selector:
    app: frontend-api
  ports:
  - port: 8080
    targetPort: 8080